name: ci
on:
  push:
    branches: [ master ]
  pull_request:

jobs:
  linux-x86_64:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Build
      run: make all dist install

    - name: Upload Artifacts
      uses: actions/upload-artifact@v2
      with:
        name: package
        path: ./*.tar.gz
        if-no-files-found: error

  freebsd-x86_64:
    runs-on: macos-12
    steps:
    - uses: actions/checkout@v2
      with:
        submodules: recursive
    - name: Run FreeBSD VM & Build
      id: termrec
      uses: vmactions/freebsd-vm@v0
      with:
        usesh: true
        prepare: pkg install -y gmake git libX11 libX11-devel
        run: |
          gmake all
          gmake install

  openbsd-x86_64:
    runs-on: macos-12
    steps:
    - uses: actions/checkout@v2
      with:
        submodules: recursive
    - name: Run OpenBSD VM & Build
      id: termrec
      uses: vmactions/openbsd-vm@v0
      with:
        usesh: true
        prepare: pkg_add gmake
        run: |
          gmake all
          gmake install

